CREATE TABLE account_entity
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance DOUBLE PRECISION,
    CONSTRAINT pk_accountentity PRIMARY KEY (id)
);

CREATE TABLE account_entity_transaction_entities
(
    account_entity_id       BIGINT NOT NULL,
    transaction_entities_id BIGINT NOT NULL
);

CREATE TABLE transaction_entity
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              TIMESTAMP with time zone,
    amount            DOUBLE PRECISION,
    operation_entity  INTEGER,
    balance           DOUBLE PRECISION,
    account_entity_id BIGINT,
    CONSTRAINT pk_transactionentity PRIMARY KEY (id)
);

ALTER TABLE account_entity_transaction_entities
    ADD CONSTRAINT uc_account_entity_transaction_entities_transactionentities UNIQUE (transaction_entities_id);

ALTER TABLE transaction_entity
    ADD CONSTRAINT FK_TRANSACTIONENTITY_ON_ACCOUNTENTITY FOREIGN KEY (account_entity_id) REFERENCES account_entity (id);

ALTER TABLE account_entity_transaction_entities
    ADD CONSTRAINT fk_accenttraent_on_account_entity FOREIGN KEY (account_entity_id) REFERENCES account_entity (id);

ALTER TABLE account_entity_transaction_entities
    ADD CONSTRAINT fk_accenttraent_on_transaction_entity FOREIGN KEY (transaction_entities_id) REFERENCES transaction_entity (id);