spring:
  profiles:
    active: test
  datasource:
    password: bank
    username: bank
    url: jdbc:postgresql://localhost:5432/bank
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      jdbc:
        time_zone: UTC
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
  flyway:
    user: sa
    password:
    url: jdbc:h2:mem:bank
    locations: filesystem:db/migration
    enabled: true
    baseline-on-migrate: true